tasks:
  - init: |
      sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform
            
      npm install commitizen -g
      commitizen init cz-conventional-changelog --save-dev --save-exact
      npm install --save-dev @commitlint/prompt @commitlint/config-conventional commitizen
      touch .git/hooks/prepare-commit-msg
      echo "exec < /dev/tty && node_modules/.bin/cz --hook || true" >> .git/hooks/prepare-commit-msg
        
      curl -L https://github.com/snyk/driftctl/releases/latest/download/driftctl_linux_amd64 -o driftctl
      chmod +x driftctl && sudo mv driftctl /usr/local/bin/
        
      curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      sudo mv ./bin/act /usr/local/bin/
        
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip && sudo ./aws/install && rm awscliv2.zip && rm -rf aws/
        
      pip install -r requirements.txt && pip install -r api/requirements.txt
      pre-commit install
    command: |
      aws configure
      terraform init
      git status

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits