tasks:
  - init: |
      pip install -r requirements.txt && pip install -r api/requirements.txt
      pre-commit install
    command: |
      bash .envrc.gitpod
      cp .envrc.gitpod .envrc

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
    - sourcegraph.cody-ai
    - donjayamanne.githistory
