# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "(api/package/.*|README.md)"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo:  https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
    #- id: shellcheck
    - id: terraform-fmt
    - id: terraform-validate
    # - id: tflint
-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
        lambda-layer
      language_version: python3
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
    -   id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ['--baseline', '.secrets.baseline']
