# .github/workflows/test01.yaml
name: check_liveness_after_site_deployment.yml

env:
   AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
   AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
   AWS_REGION: ${{secrets.AWS_REGION}}
   
   API_KEY_TEST_MAIL: ${{secrets.API_KEY_TEST_MAIL}}
   TEST_MAIL_NAMESPACE: ${{secrets.TEST_MAIL_NAMESPACE}}
   WEBSITE_URL_MAIL_NAMESPACE: "https:${GITHUB_REF_NAME}mtchoun-mouh.mongulu.cm"
   
on:
  push:
    paths:
      - '**.tf'
      - 'html/**'
      - 'api/**'
      - 'infra/templates/**' 
jobs:
  checkLivenessAfterSiteDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Install the necessary packages
        run: pip install requests webdriver-manager selenium pytest requests boto3
      - name: Run the PytTest script
        run: pytest api/test_liveness_mtchoun-mouh.py api/test_liveness_mail_reception_and_clean.py   api/test_liveness_remove_user.py
