name: Close Pull Request
# only trigger on pull request closed events
on:
  pull_request:
    types: [closed]
jobs:
  close_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_VAR_MAINTAINER_MAIL: ${{ secrets.TF_VAR_MAINTAINER_MAIL }}
      TF_VAR_WEBSITE_BUCKET_NAME: "mtchoun-mouh.mongulu.cm"
      TF_VAR_IMAGES_BUCKET_NAME: "djansang"
      TF_VAR_SENTRY_DNS: ${{ secrets.TF_VAR_SENTRY_DNS}}
      AWS_REGION: "eu-central-1"
    steps:
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - name: Install tarraform
        uses: hashicorp/setup-terraform@d22444889af304a44b997011fbabb81ff705a7b4 # ratchet:hashicorp/setup-terraform@v1.2.1
      - name: Checkout
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # ratchet:actions/checkout@v2
      - name: Install tarraform
        uses: hashicorp/setup-terraform@d22444889af304a44b997011fbabb81ff705a7b4 # ratchet:hashicorp/setup-terraform@v1.2.1
      - name: Terraform fmt
        id: fmt
        run: |
          cd infra
          terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: |
          cd infra
          terraform init
      - name: setup workspace
        id: workspace
        run: |
          cd infra
          terraform workspace select $GITHUB_HEAD_REF
      - name: Terraform Destroy
        id: destroy
        run: |
          cd infra
          terraform destroy -auto-approve
          terraform workspace select default
          terraform workspace delete $GITHUB_HEAD_REF
