name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:

  close_job:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tarraform
        uses: hashicorp/setup-terraform@v1.2.1


      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tarraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: setup workspace
        id: workspace
        run: terraform workspace select $GITHUB_HEAD_REF

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy
