name: Test Workflow
on:
  pull_request:
    branches:
      - master
    paths:
      - '**.tf'
      - 'html/**'
      - 'api/**'
      - 'templates/**'

jobs:

  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Yelp's detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0

  setup-new-env:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_MAINTAINER_MAIL: ${{ secrets.TF_VAR_MAINTAINER_MAIL }}
      TF_VAR_WEBSITE_BUCKET_NAME: "mtchoun-mouh.mongulu.cm"
      TF_VAR_IMAGES_BUCKET_NAME: ${{ secrets.TF_VAR_IMAGES_BUCKET_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tarraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: setup workspace
        id: workspace
        run: terraform workspace new $GITHUB_HEAD_REF

      - name: List workspace
        run: terraform workspace list

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Website URL
        run: terraform output website_url

      - name: Copy Site files
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: $GITHUB_HEAD_REF-${TF_VAR_WEBSITE_BUCKET_NAME}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'html'

  unittest:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install -r api/requirements.txt
      - name: test functions
        run: | 
          cd api &&  pytest test_extract.py &&\
          pytest test_notify.py
          coverage run -m pytest test_extract.py test_notify.py 
          coverage report -m
      
          