name: Main Workflow
#on:
#  schedule:
#    - cron:  '30 * * * *'
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  Ubuntu:
    name: Add labels to issues
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issue Due Dates Action
        uses: alexleventer/github-issue-due-dates-action@1.1.0
        with:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
